[package]
name = "memento-cabi"
version = "0.1.0"
authors = ["TSH Labs"]

[workspace]

[dependencies]
memento = { path = ".." }

[build-dependencies]
cbindgen = "0.3.3"

[lib]
crate-type = ["cdylib"]
