[package]
name = "memento-cabi"
version = "0.1.0"
authors = ["TSH Labs"]

[workspace]

[dependencies]
chrono = "0.4.0"
memento = { path = ".." }

[build-dependencies]
cbindgen = "0.3.3"

[lib]
name = "memento"
crate-type = ["cdylib"]
