header = "/* begin memento header */"
trailer = "/* end memento header */"
include_guard = "MEMENTO_H_INCLUDED"
language = "C"

[parse]
expand = ["memento-cabi"]

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
